[Dependencies] Update @types/promise-retry to 1.1.3
This patch fixes compile error.

@types/retry has removed WarpOptions which is used by @types/promise-retry.
If @types/promise-retry does not update will cause following error.

node_modules/@types/promise-retry/index.d.ts(7,10): error TS2305: Module '"/ai/node_modules/@types/retry/index"' has no exported member 'WrapOptions'.